package io.github.smolcan.aggrid.jpa.adapter.filter.model.simple;

public enum SimpleFilterModelType {
    empty,
    equals,
    notEqual,
    lessThan,
    lessThanOrEqual,
    greaterThan,
    greaterThanOrEqual,
    inRange,
    contains,
    notContains,
    startsWith,
    endsWith,
    blank,
    notBlank,
    
    // built-in named and relative date ranges
    today,
    yesterday,
    tomorrow,
    thisWeek,
    lastWeek,
    nextWeek,
    thisMonth,
    lastMonth,
    nextMonth,
    thisQuarter,
    lastQuarter,
    nextQuarter,
    thisYear,
    lastYear,
    nextYear,
    yearToDate,
    last7Days,
    last30Days,
    last90Days,
    last6Months,
    last12Months,
    last24Months,
    ;
}
